services:
  db:
    image: postgres:latest
    container_name: beatstar
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beatstar
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/
    restart: unless-stopped

volumes:
  pgdata:
